lib/chatter_web/router.ex
defmodule ChatterWeb.Router do
  use ChatterWeb, :router

  alias ChatterWeb.Plugs

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Doorman.Login.Session
    plug Plugs.PutUserEmail
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", ChatterWeb do
    pipe_through :browser
    get "/sign_in", SessionController, :new
    resources "/sessions", SessionController, only: [:create]
    resources "/users", UserController, only: [:new, :create]
  end

  scope "/", ChatterWeb do
    pipe_through [:browser, Plugs.RequireLogin]

    get "/", ChatRoomController, :index
    resources "/chat_rooms", ChatRoomController, only: [:new, :create, :show]
  end

  # Other scopes may use custom stacks.
  # scope "/api", ChatterWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: ChatterWeb.Telemetry
    end
  end
end

lib/chatter/accounts.ex
defmodule Chatter.Accounts do
  alias Chatter.User
  alias Chatter.Repo
  alias Doorman.Auth.Secret

  def change_user(user) do
    User.changeset(user, %{})
  end

  def create_user(params) do
    %User{}
    |> User.changeset(params)
    |> Secret.put_session_secret()
    |> Repo.insert()
  end
end

lib/chatter/application.ex
defmodule Chatter.Application do
  # See https://hexdocs.pm/elixir/Application.html
  # for more information on OTP Applications
  @moduledoc false

  use Application

  def start(_type, _args) do
    children = [
      # Start the Ecto repository
      Chatter.Repo,
      # Start the Telemetry supervisor
      ChatterWeb.Telemetry,
      # Start the PubSub system
      {Phoenix.PubSub, name: Chatter.PubSub},
      # Start the Endpoint (http/https)
      ChatterWeb.Endpoint
      # Start a worker by calling: Chatter.Worker.start_link(arg)
      # {Chatter.Worker, arg}
    ]

    # See https://hexdocs.pm/elixir/Supervisor.html
    # for other strategies and supported options
    opts = [strategy: :one_for_one, name: Chatter.Supervisor]
    Supervisor.start_link(children, opts)
  end

  # Tell Phoenix to update the endpoint configuration
  # whenever the application is updated.
  def config_change(changed, _new, removed) do
    ChatterWeb.Endpoint.config_change(changed, removed)
    :ok
  end
end

lib/chatter/chat.ex
defmodule Chatter.Chat do
  alias Chatter.Chat.Room
  alias Chatter.Chat.Room.Message
  alias Chatter.Repo
  import Ecto.Query

  def all_rooms do
    Room |> Repo.all()
  end

  def new_chat_room do
    %Room{}
    |> Room.changeset(%{})
  end

  def create_chat_room(params) do
    %Room{}
    |> Room.changeset(params)
    |> Repo.insert()
  end

  def find_room(id) do
    Room |> Repo.get!(id)
  end

  def find_room_by_name(name) do
    Room |> Repo.get_by!(name: name)
  end

  def new_message(room, params) do
    room
    |> Ecto.build_assoc(:messages)
    |> Message.changeset(params)
    |> Repo.insert()
  end

  def room_messages(room) do
    Message
    |> where([m], m.chat_room_id == ^room.id)
    |> Repo.all()
  end
end

lib/chatter/chat/room.ex
defmodule Chatter.Chat.Room do
  use Ecto.Schema
  import Ecto.Changeset
  alias Chatter.Chat.Room.Message

  schema "chat_rooms" do
    field :name, :string
    has_many :messages, Message, foreign_key: :chat_room_id

    timestamps()
  end

  def changeset(struct, attrs) do
    struct
    |> cast(attrs, [:name])
    |> validate_required([:name])
    |> unique_constraint(:name)
  end
end

lib/chatter/chat/room/message.ex
defmodule Chatter.Chat.Room.Message do
  use Ecto.Schema
  import Ecto.Changeset

  @derive {Jason.Encoder, only: [:author, :body, :chat_room_id]}
  schema "chat_room_messages" do
    field :author, :string
    field :body, :string
    belongs_to :chat_room, Chatter.Chat.Room

    timestamps()
  end

  @doc false
  def changeset(message, attrs) do
    message
    |> cast(attrs, [:author, :body, :chat_room_id])
    |> validate_required([:author, :body, :chat_room_id])
  end
end

lib/chatter/repo.ex
defmodule Chatter.Repo do
  use Ecto.Repo,
    otp_app: :chatter,
    adapter: Ecto.Adapters.Postgres
end

lib/chatter/user.ex
defmodule Chatter.User do
  use Ecto.Schema
  import Ecto.Changeset
  import Doorman.Auth.Bcrypt, only: [hash_password: 1]

  schema "users" do
    field :email, :string
    field :hashed_password, :string
    field :session_secret, :string
    field :password, :string, virtual: true

    timestamps()
  end

  @doc false
  def changeset(user, attrs) do
    user
    |> cast(attrs, [:email, :password])
    |> validate_required([:email, :password])
    |> hash_password()
    |> unique_constraint(:email)
  end
end

lib/chatter_web/controllers/chat_room_controller.ex
defmodule ChatterWeb.ChatRoomController do
  alias Chatter.Chat
  use ChatterWeb, :controller

  def index(conn, _params) do
    chat_rooms = Chatter.Chat.all_rooms()

    render(conn, "index.html", chat_rooms: chat_rooms)
  end

  def new(conn, _params) do
    changeset = Chat.new_chat_room()
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"room" => room_params}) do
    case Chat.create_chat_room(room_params) do
      {:ok, room} -> redirect(conn, to: Routes.chat_room_path(conn, :show, room))
      {:error, changeset} -> render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    room = Chatter.Chat.find_room(id)
    render(conn, "show.html", chat_room: room)
  end
end

lib/chatter_web/controllers/session_controller.ex
defmodule ChatterWeb.SessionController do
  use ChatterWeb, :controller

  def new(conn, _) do
    render(conn, "new.html")
  end

  def create(conn, %{"email" => email, "password" => password}) do
    case Doorman.authenticate(email, password) do
      nil ->
        conn
        |> put_flash(:error, "Invalid email or password")
        |> render("new.html")

      user ->
        conn
        |> Doorman.Login.Session.login(user)
        |> redirect(to: "/")
    end
  end
end

lib/chatter_web/controllers/user_controller.ex
defmodule ChatterWeb.UserController do
  use ChatterWeb, :controller
  alias Chatter.User
  alias Doorman.Login.Session
  alias Chatter.Accounts

  def new(conn, _params) do
    changeset = Accounts.change_user(%User{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"user" => params}) do
    case Accounts.create_user(params) do
      {:ok, user} ->
        conn
        |> Session.login(user)
        |> redirect(to: "/")

      {:error, changeset} ->
        conn
        |> render("new.html", changeset: changeset)
    end
  end
end

lib/chatter_web/views/error_view.ex
defmodule ChatterWeb.ErrorView do
  use ChatterWeb, :view

  # If you want to customize a particular status code
  # for a certain format, you may uncomment below.
  # def render("500.html", _assigns) do
  #   "Internal Server Error"
  # end

  # By default, Phoenix returns the status message from
  # the template name. For example, "404.html" becomes
  # "Not Found".
  def template_not_found(template, _assigns) do
    Phoenix.Controller.status_message_from_template(template)
  end
end

lib/chatter_web/views/layout_view.ex
defmodule ChatterWeb.LayoutView do
  use ChatterWeb, :view
end

lib/chatter_web/views/session_view.ex
defmodule ChatterWeb.SessionView do
  use ChatterWeb, :view
end

lib/chatter_web/views/user_view.ex
defmodule ChatterWeb.UserView do
  use ChatterWeb, :view
end

lib/chatter_web/templates/chat_room/index.html.eex
<h1 class="title">Welcome to Chatter!</h1>

<ul>
  <%= for room <- @chat_rooms do %>
    <li data-role="room">
      <%= link room.name, to: Routes.chat_room_path(@conn, :show, room) %>
    </li>
  <% end %>
</ul>

<div>
  <%= link "New chat room", to: Routes.chat_room_path(@conn, :new) %>
</div>

lib/chatter_web/templates/chat_room/new.html.eex
<div>
  <%= form_for @changeset, Routes.chat_room_path(@conn, :create), fn f -> %>
    <label>
      Name:
      <%= error_tag f, :name %>
      <%= text_input f, :name %>
    </label>

    <%= submit "Submit" %>
  <% end %>
</div>

lib/chatter_web/templates/chat_room/show.html.eex
<%= content_tag(:h1, id: "chat-room-title", data: [role: "room-title", chat_room_name: @chat_room.name]) do %>
  <%= @chat_room.name %>
<% end %>

<div>
  <ul data-role="messages">
  </ul>
</div>

<form id="new-message-form">
  <label>
    New Message <input id="message" name="message" type="text" />
  </label>

  <button type="submit">Send</button>
</form>

lib/chatter_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Chatter · Phoenix Framework</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
    <script>window.email = "<%= assigns[:email] %>";</script>
    <script defer type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </head>
  <body>
    <header>
      <section class="container">
        <nav role="navigation">
          <ul>
            <li><a href="https://hexdocs.pm/phoenix/overview.html">Get Started</a></li>
            <%= if function_exported?(Routes, :live_dashboard_path, 2) do %>
              <li><%= link "LiveDashboard", to: Routes.live_dashboard_path(@conn, :home) %></li>
            <% end %>
          </ul>
        </nav>
        <a href="https://phoenixframework.org/" class="phx-logo">
          <img src="<%= Routes.static_path(@conn, "/images/phoenix.png") %>" alt="Phoenix Framework Logo"/>
        </a>
      </section>
    </header>
    <main role="main" class="container">
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <%= @inner_content %>
    </main>
  </body>
</html>

lib/chatter_web/templates/session/new.html.eex
<%= form_for @conn, Routes.session_path(@conn, :create), fn f -> %>
  <label>
    Email: <%= text_input f, :email %>
  </label>

  <label>
    Password: <%= password_input f, :password %>
  </label>

  <%= submit "Sign in" %>
<% end %>


<div>
  <p>Don't have an account?</p>
  <%= link "Create an account", to: Routes.user_path(@conn, :new) %>
</div>

lib/chatter_web/templates/user/new.html.eex
<%= form_for @changeset, Routes.user_path(@conn, :create), fn f -> %>
  <label>
    Email: <%= text_input f, :email %>
    <%= error_tag f, :email %>
  </label>

  <label>
    Password: <%= password_input f, :password %>
    <%= error_tag f, :password %>
  </label>

  <%= submit "Sign up" %>
<% end %>